# -*- coding: utf-8 -*-
"""book_recommender_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PLfWqAL_y8PPYnNWSs4iPwuwcOlOTcQn
"""

app_code = """
import streamlit as st
import pickle
import pandas as pd

st.title("📚 Book Recommender")

with open("model.pkl", "rb") as f:
    model = pickle.load(f)

#books = pd.read_csv("books.csv")

book_description = st.text_input("Enter a book description:")

if st.button("Recommend"):
    st.write("Recommendations will appear here.")
"""

with open("app.py", "w") as f:
    f.write(app_code)